# Generated by Django 4.2.5 on 2023-10-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("url", models.URLField(default="www.google.com", max_length=254)),
                ("contenu", models.TextField()),
                (
                    "description",
                    models.TextField(
                        default=" Dans ce cours, nous allons corriger, ensemble, cette mauvaise posture qui est à lorigine de votre stress, de vos maux de tête et linconfort global que vous ressentez.Jai conçu ce cours de programmation pour qu'il soit accessible aux débutants.",
                        max_length=254,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "email",
                    models.EmailField(default="Bendemba@gmail.com", max_length=254),
                ),
                ("phone", models.IntegerField(null=True)),
                ("matricule", models.FloatField(default=2088077)),
            ],
        ),
    ]
