# Generated by Django 4.2.6 on 2023-10-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cour",
            name="contenu",
        ),
        migrations.AddField(
            model_name="cour",
            name="etudiant",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.etudiant",
            ),
            preserve_default=False,
        ),
    ]
