# Generated by Django 4.2.6 on 2023-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_remove_cour_contenu_cour_etudiant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cour",
            name="note",
            field=models.FloatField(default=11),
        ),
    ]
